#!/bin/bash
echo "Installing OpenJVS..."

# Compile the project
echo "Compiling Project"
cd ..
make -s
cd scripts

# Create config
echo "Creating Config in /etc/OpenJVS"
mkdir -p /etc/OpenJVS
cp -rn ../docs/config/ /etc/OpenJVS

# Copy Executable
echo "Copying over executable to /usr/bin/openjvs"
sudo cp ../bin/openjvs /usr/bin/.
sudo cp openjvs-pi /usr/bin/.

echo "Installed"
