#!/bin/bash
echo "Uninstalling..."

echo "Removing executables from /usr/bin/openjvs"
sudo rm /usr/bin/openjvs
sudo rm /usr/bin/openjvs-pi

echo "Remove config files"
sudo rm -rf /etc/OpenJVS

echo "Uninstall finished"
